apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ex828267l-go 
  janus-idp.io/tekton: ex828267l-go
  backstage.io/kubernetes-id: ex828267l-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ex828267l-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml